### ISSUE TITLE
Proporsal Logo TRENDChecker

### ISSUE THREAD

**Issue by familqasimov** [ko-redtruck/trendchecker#3]
Hi sir @wil1liam. It was a little late for the task. I'm sorry. I created a logo in the form of a pen reminiscent of the robot. The pen marks on the trend and points out in the small squares of the pen's head. I think you like it.

![untitled-1](https://user-images.githubusercontent.com/36432269/38286993-4d1854e6-37d9-11e8-8a03-cea6a3e06731.png)

**Comment by ko-redtruck** [comment]
Thanks for your contribution!
